using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WordFlashCards.TextTokenizer;

namespace WordFlashCards.English
{
    public class PhrasalVerbList
    {
        private List<PhrasalVerb> _phrasalVerbs;

        public PhrasalVerbList()
        {
            InitializePhrasalVerbs();
        }

        public IEnumerable<PhrasalVerb> FindPhrasalVerb(ITokenizer tokenizer, string initialVerb)
        {
            var result = new List<PhrasalVerb>();

            var possibleList = _phrasalVerbs.Where(pv => pv.InitialVerb == initialVerb);

            foreach (var pv in possibleList)
            {
                if (pv.TestRule(tokenizer))
                    result.Add(pv);
            }

            return result;
        }

        private void InitializePhrasalVerbs()
        {
            _phrasalVerbs = new List<PhrasalVerb>()
            {
                new PhrasalVerb("act", "act up"),
                new PhrasalVerb("add", "add up to"),
                new PhrasalVerb("add", "add * up"),
                new PhrasalVerb("add", "add up"),
                new PhrasalVerb("ask", "ask * out"),
                new PhrasalVerb("ask", "ask * over"),
                new PhrasalVerb("back", "back * up"),
                new PhrasalVerb("back", "back down"),
                new PhrasalVerb("back", "back out of"),
                new PhrasalVerb("back", "back out"),
                new PhrasalVerb("back", "back up"),
                new PhrasalVerb("bawl", "bawl * out"),
                new PhrasalVerb("bear", "bear down on"),
                new PhrasalVerb("bear", "bear on"),
                new PhrasalVerb("bear", "bear up under"),
                new PhrasalVerb("bear", "bear up"),
                new PhrasalVerb("bear", "bear with"),
                new PhrasalVerb("blow", "blow * up"),
                new PhrasalVerb("blow", "blow in"),
                new PhrasalVerb("blow", "blow over"),
                new PhrasalVerb("blow", "blow up"),
                new PhrasalVerb("break", "break * down"),
                new PhrasalVerb("break", "break * in"),
                new PhrasalVerb("break", "break * off"),
                new PhrasalVerb("break", "break * up"),
                new PhrasalVerb("break", "break down"),
                new PhrasalVerb("break", "break in on"),
                new PhrasalVerb("break", "break in"),
                new PhrasalVerb("break", "break into"),
                new PhrasalVerb("break", "break out of"),
                new PhrasalVerb("break", "break out"),
                new PhrasalVerb("break", "break up"),
                new PhrasalVerb("bring", "bring * about"),
                new PhrasalVerb("bring", "bring * along"),
                new PhrasalVerb("bring", "bring * around"),
                new PhrasalVerb("bring", "bring * away"),
                new PhrasalVerb("bring", "bring * off"),
                new PhrasalVerb("bring", "bring * on"),
                new PhrasalVerb("bring", "bring * out"),
                new PhrasalVerb("bring", "bring * over"),
                new PhrasalVerb("bring", "bring * to"),
                new PhrasalVerb("bring", "bring * up"),
                new PhrasalVerb("brush", "brush * off"),
                new PhrasalVerb("burn", "burn * down"),
                new PhrasalVerb("burn", "burn * up"),
                new PhrasalVerb("burn", "burn down"),
                new PhrasalVerb("burn", "burn up"),
                new PhrasalVerb("burn", "burn up"),
                new PhrasalVerb("buy", "buy * out"),
                new PhrasalVerb("buy", "buy * up"),
                new PhrasalVerb("call", "call * off"),
                new PhrasalVerb("call", "call * up"),
                new PhrasalVerb("call", "call for"),
                new PhrasalVerb("call", "call on"),
                new PhrasalVerb("calm", "calm * down"),
                new PhrasalVerb("care", "care for"),
                new PhrasalVerb("carry", "carry * out"),
                new PhrasalVerb("carry", "carry * over"),
                new PhrasalVerb("carry", "carry on about"),
                new PhrasalVerb("carry", "carry on with"),
                new PhrasalVerb("carry", "carry on"),
                new PhrasalVerb("catch", "catch up on"),
                new PhrasalVerb("catch", "catch up with"),
                new PhrasalVerb("catch", "catch up"),
                new PhrasalVerb("catch", "catch on"),
                new PhrasalVerb("check", "check * off"),
                new PhrasalVerb("check", "check * over"),
                new PhrasalVerb("check", "check * through"),
                new PhrasalVerb("check", "check back"),
                new PhrasalVerb("check", "check by"),
                new PhrasalVerb("check", "check for"),
                new PhrasalVerb("check", "check in"),
                new PhrasalVerb("check", "check into"),
                new PhrasalVerb("check", "check on"),
                new PhrasalVerb("check", "check out of"),
                new PhrasalVerb("check", "check out"),
                new PhrasalVerb("check", "check * out"),
                new PhrasalVerb("check", "check up on"),
                new PhrasalVerb("check", "check with"),
                new PhrasalVerb("cheer", "cheer * up"),
                new PhrasalVerb("cheer", "cheer up"),
                new PhrasalVerb("chew", "chew * up"),
                new PhrasalVerb("chop", "chop * down"),
                new PhrasalVerb("chop", "chop * up"),
                new PhrasalVerb("clean", "clean * up"),
                new PhrasalVerb("clear", "clear * up"),
                new PhrasalVerb("clear", "clear out"),
                new PhrasalVerb("close", "close * down"),
                new PhrasalVerb("close", "close * up"),
                new PhrasalVerb("close", "close down"),
                new PhrasalVerb("close", "close in on"),
                new PhrasalVerb("close", "close up"),
                new PhrasalVerb("come", "come about"),
                new PhrasalVerb("come", "come across"),
                new PhrasalVerb("come", "come along with"),
                new PhrasalVerb("come", "come along"),
                new PhrasalVerb("come", "come away"),
                new PhrasalVerb("come", "come back"),
                new PhrasalVerb("come", "come by"),
                new PhrasalVerb("come", "come by"),
                new PhrasalVerb("come", "come down with"),
                new PhrasalVerb("come", "come into"),
                new PhrasalVerb("come", "come off"),
                new PhrasalVerb("come", "come out with"),
                new PhrasalVerb("come", "come out"),
                new PhrasalVerb("come", "come over"),
                new PhrasalVerb("come", "come through"),
                new PhrasalVerb("come", "come to"),
                new PhrasalVerb("come", "come up to"),
                new PhrasalVerb("come", "come up with"),
                new PhrasalVerb("come", "come with"),
                new PhrasalVerb("count", "count * in"),
                new PhrasalVerb("count", "count * out"),
                new PhrasalVerb("count", "count * up"),
                new PhrasalVerb("count", "count on"),
                new PhrasalVerb("crack", "crack down on"),
                new PhrasalVerb("crack", "crack up at"),
                new PhrasalVerb("crack", "crack up"),
                new PhrasalVerb("cross", "cross * out"),
                new PhrasalVerb("cut", "cut * off"),
                new PhrasalVerb("cut", "cut * out"),
                new PhrasalVerb("cut", "cut * up"),
                new PhrasalVerb("cut", "cut down on"),
                new PhrasalVerb("cut", "cut down"),
                new PhrasalVerb("cut", "cut in on"),
                new PhrasalVerb("cut", "cut in"),
                new PhrasalVerb("die", "die away"),
                new PhrasalVerb("die", "die down"),
                new PhrasalVerb("die", "die off"),
                new PhrasalVerb("die", "die out"),
                new PhrasalVerb("disagree", "disagree with"),
                new PhrasalVerb("do", "do * over"),
                new PhrasalVerb("do", "do away with"),
                new PhrasalVerb("do", "do without"),
                new PhrasalVerb("draw", "draw * up"),
                new PhrasalVerb("dress", "dress * down"),
                new PhrasalVerb("dress", "dress * up"),
                new PhrasalVerb("dress", "dress down"),
                new PhrasalVerb("dress", "dress up"),
                new PhrasalVerb("drive", "drive * back"),
                new PhrasalVerb("drop", "drop in on"),
                new PhrasalVerb("drop", "drop in"),
                new PhrasalVerb("drop", "drop out of"),
                new PhrasalVerb("drop", "drop out"),
                new PhrasalVerb("drop", "drop over"),
                new PhrasalVerb("eat", "eat * up"),
                new PhrasalVerb("eat", "eat away"),
                new PhrasalVerb("eat", "eat in"),
                new PhrasalVerb("eat", "eat out"),
                new PhrasalVerb("face", "face up to"),
                new PhrasalVerb("fall", "fall back on"),
                new PhrasalVerb("fall", "fall behind in"),
                new PhrasalVerb("fall", "fall behind"),
                new PhrasalVerb("fall", "fall off"),
                new PhrasalVerb("fall", "fall out with"),
                new PhrasalVerb("fall", "fall through"),
                new PhrasalVerb("feel", "feel * up"),
                new PhrasalVerb("feel", "feel up to"),
                new PhrasalVerb("figure", "figure * out"),
                new PhrasalVerb("figure", "figure * up"),
                new PhrasalVerb("figure", "figure on"),
                new PhrasalVerb("fill", "fill * out"),
                new PhrasalVerb("fill", "fill * up"),
                new PhrasalVerb("fill", "fill in for"),
                new PhrasalVerb("fill", "fill in"),
                new PhrasalVerb("fill", "fill out"),
                new PhrasalVerb("fill", "fill * in"),
                new PhrasalVerb("find", "find out"),
                new PhrasalVerb("fix", "fix * up"),
                new PhrasalVerb("get", "get ahead of"),
                new PhrasalVerb("get", "get ahead"),
                new PhrasalVerb("get", "get along with"),
                new PhrasalVerb("get", "get along"),
                new PhrasalVerb("get", "get around"),
                new PhrasalVerb("get", "get away with"),
                new PhrasalVerb("get", "get away"),
                new PhrasalVerb("get", "get by on"),
                new PhrasalVerb("get", "get by with"),
                new PhrasalVerb("get", "get by"),
                new PhrasalVerb("get", "get down to"),
                new PhrasalVerb("get", "get in"),
                new PhrasalVerb("get", "get off"),
                new PhrasalVerb("get", "get rid of"),
                new PhrasalVerb("get", "get on with"),
                new PhrasalVerb("get", "get on"),
                new PhrasalVerb("get", "get out of"),
                new PhrasalVerb("get", "get over"),
                new PhrasalVerb("get", "get through with"),
                new PhrasalVerb("get", "get through to"),
                new PhrasalVerb("get", "get through"),
                new PhrasalVerb("get", "get up"),
                new PhrasalVerb("get", "get * across"),
                new PhrasalVerb("get", "get * off"),
                new PhrasalVerb("get", "get * on"),
                new PhrasalVerb("get", "get * up"),
                new PhrasalVerb("give", "give * away"),
                new PhrasalVerb("give", "give * back"),
                new PhrasalVerb("give", "give * out"),
                new PhrasalVerb("give", "give * up"),
                new PhrasalVerb("give", "give in"),
                new PhrasalVerb("give", "give out"),
                new PhrasalVerb("give", "give up"),
                new PhrasalVerb("give", "give off"),
                new PhrasalVerb("go", "go away"),
                new PhrasalVerb("go", "go back on"),
                new PhrasalVerb("go", "go back"),
                new PhrasalVerb("go", "go by"),
                new PhrasalVerb("go", "go down"),
                new PhrasalVerb("go", "go for"),
                new PhrasalVerb("go", "go in for"),
                new PhrasalVerb("go", "go into"),
                new PhrasalVerb("go", "go off"),
                new PhrasalVerb("go", "go on with"),
                new PhrasalVerb("go", "go on"),
                new PhrasalVerb("go", "go out"),
                new PhrasalVerb("go", "go over"),
                new PhrasalVerb("go", "go through with"),
                new PhrasalVerb("go", "go through"),
                new PhrasalVerb("go", "go with"),
                new PhrasalVerb("go", "go without"),
                new PhrasalVerb("grow", "grow under"),
                new PhrasalVerb("grow", "grow up"),
                new PhrasalVerb("hand", "hand * back"),
                new PhrasalVerb("hand", "hand * down"),
                new PhrasalVerb("hand", "hand * in"),
                new PhrasalVerb("hand", "hand * out"),
                new PhrasalVerb("hand", "hand * over"),
                new PhrasalVerb("hang", "hang * up"),
                new PhrasalVerb("hang", "hang around"),
                new PhrasalVerb("hang", "hang out"),
                new PhrasalVerb("hang", "hang up"),
                new PhrasalVerb("have", "have * on"),
                new PhrasalVerb("have", "have * over"),
                new PhrasalVerb("hear", "hear from"),
                new PhrasalVerb("hear", "hear of"),
                new PhrasalVerb("hit", "hit on"),
                new PhrasalVerb("hold", "hold back"),
                new PhrasalVerb("hold", "hold off on"),
                new PhrasalVerb("hold", "hold on to"),
                new PhrasalVerb("hold", "hold on"),
                new PhrasalVerb("hold", "hold out against"),
                new PhrasalVerb("hold", "hold out"),
                new PhrasalVerb("hold", "hold * back"),
                new PhrasalVerb("hold", "hold * off"),
                new PhrasalVerb("hold", "hold * up"),
                new PhrasalVerb("hook", "hook * up"),
                new PhrasalVerb("iron", "iron * out"),
                new PhrasalVerb("jack", "jack up"),
                new PhrasalVerb("joke", "joke around"),
                new PhrasalVerb("jump", "jump in"),
                new PhrasalVerb("jump", "jump to"),
                new PhrasalVerb("keep", "keep at"),
                new PhrasalVerb("keep", "keep on"),
                new PhrasalVerb("keep", "keep to"),
                new PhrasalVerb("keep", "keep up with"),
                new PhrasalVerb("keep", "keep up"),
                new PhrasalVerb("keep", "keep * around"),
                new PhrasalVerb("keep", "keep * away"),
                new PhrasalVerb("keep", "keep * back"),
                new PhrasalVerb("keep", "keep * down"),
                new PhrasalVerb("keep", "keep * in"),
                new PhrasalVerb("keep", "keep * off"),
                new PhrasalVerb("keep", "keep * out"),
                new PhrasalVerb("keep", "keep * over"),
                new PhrasalVerb("keep", "keep * up"),
                new PhrasalVerb("kick", "kick back"),
                new PhrasalVerb("kick", "kick in"),
                new PhrasalVerb("lay", "lay * off"),
                new PhrasalVerb("lay", "lay * out"),
                new PhrasalVerb("lay", "lay down"),
                new PhrasalVerb("lay", "lay in on"),
                new PhrasalVerb("lay", "lay into"),
                new PhrasalVerb("lay", "lay away"),
                new PhrasalVerb("leave", "leave * out"),
                new PhrasalVerb("let", "let up"),
                new PhrasalVerb("let", "let * down"),
                new PhrasalVerb("let", "let * out"),
                new PhrasalVerb("lie", "lie down on"),
                new PhrasalVerb("lie", "lie down"),
                new PhrasalVerb("lie", "lie with"),
                new PhrasalVerb("light", "light * up"),
                new PhrasalVerb("light", "light up"),
                new PhrasalVerb("live", "live * down"),
                new PhrasalVerb("live", "live on"),
                new PhrasalVerb("live", "live up to"),
                new PhrasalVerb("look", "look after"),
                new PhrasalVerb("look", "look back on"),
                new PhrasalVerb("look", "look down on"),
                new PhrasalVerb("look", "look for"),
                new PhrasalVerb("look", "look forward to"),
                new PhrasalVerb("look", "look into"),
                new PhrasalVerb("look", "look on"),
                new PhrasalVerb("look", "look out"),
                new PhrasalVerb("look", "look up to"),
                new PhrasalVerb("look", "look * over"),
                new PhrasalVerb("look", "look * up"),
                new PhrasalVerb("make", "make out with"),
                new PhrasalVerb("make", "make out"),
                new PhrasalVerb("make", "make up for"),
                new PhrasalVerb("make", "make up"),
                new PhrasalVerb("make", "make * out"),
                new PhrasalVerb("make", "make * over"),
                new PhrasalVerb("make", "make * up"),
                new PhrasalVerb("mix", "mix * up"),
                new PhrasalVerb("name", "name * after"),
                new PhrasalVerb("nod", "nod off"),
                new PhrasalVerb("nose", "nose around"),
                new PhrasalVerb("occur", "occur to"),
                new PhrasalVerb("open", "open up"),
                new PhrasalVerb("out", "out to verb"),
                new PhrasalVerb("pan", "pan out"),
                new PhrasalVerb("pass", "pass * off"),
                new PhrasalVerb("pass", "pass * on"),
                new PhrasalVerb("pass", "pass * out"),
                new PhrasalVerb("pass", "pass * up"),
                new PhrasalVerb("pass", "pass away"),
                new PhrasalVerb("pass", "pass on"),
                new PhrasalVerb("pass", "pass out"),
                new PhrasalVerb("pay", "pay * back"),
                new PhrasalVerb("pay", "pay * off"),
                new PhrasalVerb("pick", "pick * out"),
                new PhrasalVerb("pick", "pick * up"),
                new PhrasalVerb("pick", "pick on"),
                new PhrasalVerb("pick", "pick up"),
                new PhrasalVerb("play", "play * down"),
                new PhrasalVerb("play", "play * up"),
                new PhrasalVerb("play", "play up to"),
                new PhrasalVerb("point", "point * out"),
                new PhrasalVerb("pull", "pull down"),
                new PhrasalVerb("pull", "pull in"),
                new PhrasalVerb("pull", "pull out"),
                new PhrasalVerb("pull", "pull through"),
                new PhrasalVerb("put", "put in"),
                new PhrasalVerb("put", "put out"),
                new PhrasalVerb("put", "put up with"),
                new PhrasalVerb("put", "put * across"),
                new PhrasalVerb("put", "put * away"),
                new PhrasalVerb("put", "put * down"),
                new PhrasalVerb("put", "put * off"),
                new PhrasalVerb("put", "put * on"),
                new PhrasalVerb("put", "put * out"),
                new PhrasalVerb("put", "put * up"),
                new PhrasalVerb("quiet", "quiet * down"),
                new PhrasalVerb("read", "read up on"),
                new PhrasalVerb("ring", "ring * up"),
                new PhrasalVerb("rule", "rule * out"),
                new PhrasalVerb("run", "run across"),
                new PhrasalVerb("run", "run against"),
                new PhrasalVerb("run", "run away from"),
                new PhrasalVerb("run", "run away"),
                new PhrasalVerb("run", "run down"),
                new PhrasalVerb("run", "run for"),
                new PhrasalVerb("run", "run into"),
                new PhrasalVerb("run", "run off"),
                new PhrasalVerb("run", "run out of"),
                new PhrasalVerb("run", "run * down"),
                new PhrasalVerb("run", "run * off"),
                new PhrasalVerb("save", "save * up"),
                new PhrasalVerb("see", "see * off"),
                new PhrasalVerb("see", "see * through"),
                new PhrasalVerb("see", "see about"),
                new PhrasalVerb("see", "see to"),
                new PhrasalVerb("sell", "sell * out"),
                new PhrasalVerb("set", "set * up"),
                new PhrasalVerb("set", "set * up"),
                new PhrasalVerb("set", "set up"),
                new PhrasalVerb("settle", "settle on"),
                new PhrasalVerb("settle", "settle up"),
                new PhrasalVerb("show", "show * off"),
                new PhrasalVerb("show", "show * up"),
                new PhrasalVerb("show", "show off"),
                new PhrasalVerb("show", "show up"),
                new PhrasalVerb("shut", "shut * off"),
                new PhrasalVerb("shut", "shut * up"),
                new PhrasalVerb("slow", "slow * down"),
                new PhrasalVerb("slow", "slow * up"),
                new PhrasalVerb("spell", "spell * out"),
                new PhrasalVerb("stand", "stand by"),
                new PhrasalVerb("stand", "stand for"),
                new PhrasalVerb("stand", "stand out"),
                new PhrasalVerb("stand", "stand up for"),
                new PhrasalVerb("stand", "stand up to"),
                new PhrasalVerb("stand", "stand * up"),
                new PhrasalVerb("stay", "stay over"),
                new PhrasalVerb("stick", "stick it to"),
                new PhrasalVerb("stick", "stick to"),
                new PhrasalVerb("stick", "stick up for"),
                new PhrasalVerb("take", "take after"),
                new PhrasalVerb("take", "take off"),
                new PhrasalVerb("take", "take on"),
                new PhrasalVerb("take", "take over"),
                new PhrasalVerb("take", "take up"),
                new PhrasalVerb("take", "take * away"),
                new PhrasalVerb("take", "take * back"),
                new PhrasalVerb("take", "take * down"),
                new PhrasalVerb("take", "take * for"),
                new PhrasalVerb("take", "take * in"),
                new PhrasalVerb("take", "take * off"),
                new PhrasalVerb("take", "take * out"),
                new PhrasalVerb("take", "take * over"),
                new PhrasalVerb("take", "take * up"),
                new PhrasalVerb("talk", "talk * over"),
                new PhrasalVerb("talk", "talk back to"),
                new PhrasalVerb("talk", "talk back"),
                new PhrasalVerb("tear", "tear * down"),
                new PhrasalVerb("tear", "tear * up"),
                new PhrasalVerb("tell", "tell * off"),
                new PhrasalVerb("tell", "tell on"),
                new PhrasalVerb("think", "think * over"),
                new PhrasalVerb("think", "think * through"),
                new PhrasalVerb("think", "think * up"),
                new PhrasalVerb("throw", "throw * away"),
                new PhrasalVerb("throw", "throw * out"),
                new PhrasalVerb("throw", "throw up"),
                new PhrasalVerb("tie", "tie * up"),
                new PhrasalVerb("tire", "tire * out"),
                new PhrasalVerb("touch", "touch * up"),
                new PhrasalVerb("touch", "touch on"),
                new PhrasalVerb("try", "try * on"),
                new PhrasalVerb("try", "try * out"),
                new PhrasalVerb("turn", "turn in"),
                new PhrasalVerb("turn", "turn into"),
                new PhrasalVerb("turn", "turn on"),
                new PhrasalVerb("turn", "turn out"),
                new PhrasalVerb("turn", "turn up"),
                new PhrasalVerb("turn", "turn * around"),
                new PhrasalVerb("turn", "turn * away"),
                new PhrasalVerb("turn", "turn * down"),
                new PhrasalVerb("turn", "turn * in"),
                new PhrasalVerb("turn", "turn * off"),
                new PhrasalVerb("turn", "turn * on"),
                new PhrasalVerb("turn", "turn * out"),
                new PhrasalVerb("turn", "turn * over"),
                new PhrasalVerb("turn", "turn * up"),
                new PhrasalVerb("use", "use * up"),
                new PhrasalVerb("veer", "veer away from"),
                new PhrasalVerb("wait", "wait on"),
                new PhrasalVerb("wait", "wait up for"),
                new PhrasalVerb("wait", "wait up"),
                new PhrasalVerb("wake", "wake * up"),
                new PhrasalVerb("wake", "wake up"),
                new PhrasalVerb("wash", "wash * up"),
                new PhrasalVerb("wash", "wash up"),
                new PhrasalVerb("watch", "watch out for"),
                new PhrasalVerb("watch", "watch out"),
                new PhrasalVerb("wear", "wear * out"),
                new PhrasalVerb("wear", "wear off"),
                new PhrasalVerb("wind", "wind * up"),
                new PhrasalVerb("wind", "wind up"),
                new PhrasalVerb("wipe", "wipe * out"),
                new PhrasalVerb("wipe", "wipe * out"),
                new PhrasalVerb("work", "work * out"),
                new PhrasalVerb("work", "work out"),
                new PhrasalVerb("write", "write * down"),
                new PhrasalVerb("write", "write * out"),
                new PhrasalVerb("write", "write * up"),
                new PhrasalVerb("yak", "yak on about"),
                new PhrasalVerb("yak", "yak on"),
                new PhrasalVerb("yammer", "yammer on about"),
                new PhrasalVerb("yammer", "yammer on"),
                new PhrasalVerb("zero", "zero in on"),
                new PhrasalVerb("zip", "zip around"),
                new PhrasalVerb("zone", "zone out"),
                new PhrasalVerb("zonk", "zonk out"),
                new PhrasalVerb("zoom", "zoom in on"),
                new PhrasalVerb("zoom", "zoom in")
            };
        }
    }
}
